apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: knote-app
data:
  .dockerconfigjson: ICAgICAgICBhdXRoczogewogICAgICAgICAgICAgICAgaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvOiB7fQogICAgICAgIH0sCiAgICAgICAgY3JlZHNTdG9yZTogZGVza3RvcC5leGUgCg==
type: kubernetes.io/dockerconfigjson